// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fOGtriTZWSAQ4sMjZfMgsCaEp6KBa60',
    appId: '1:773183996238:web:498449ee5b606296abde1f',
    messagingSenderId: '773183996238',
    projectId: 'nova-care-f4b80',
    authDomain: 'nova-care-f4b80.firebaseapp.com',
    storageBucket: 'nova-care-f4b80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKBKxn0xwmhm2WQ3-M41bYQIj2BgpnVZo',
    appId: '1:773183996238:android:97508e0315997bf0abde1f',
    messagingSenderId: '773183996238',
    projectId: 'nova-care-f4b80',
    storageBucket: 'nova-care-f4b80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvDqdDOeJuttXNthabJLIPRSFdh-uaA0s',
    appId: '1:773183996238:ios:96f2bdc2ac070addabde1f',
    messagingSenderId: '773183996238',
    projectId: 'nova-care-f4b80',
    storageBucket: 'nova-care-f4b80.firebasestorage.app',
    iosBundleId: 'com.example.novaCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvDqdDOeJuttXNthabJLIPRSFdh-uaA0s',
    appId: '1:773183996238:ios:96f2bdc2ac070addabde1f',
    messagingSenderId: '773183996238',
    projectId: 'nova-care-f4b80',
    storageBucket: 'nova-care-f4b80.firebasestorage.app',
    iosBundleId: 'com.example.novaCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8fOGtriTZWSAQ4sMjZfMgsCaEp6KBa60',
    appId: '1:773183996238:web:f04672d5a4d32f70abde1f',
    messagingSenderId: '773183996238',
    projectId: 'nova-care-f4b80',
    authDomain: 'nova-care-f4b80.firebaseapp.com',
    storageBucket: 'nova-care-f4b80.firebasestorage.app',
  );

}